---
# tasks file for mysql

- name: Install mysql
  apt: name={{ item }} state=installed
  with_items:
    - python-selinux
    - mysql-server
    - python-mysqldb

- name: Generate new root password
  command: openssl rand -hex 7
  register: mysql_new_root_pass

- name: Remove anonymous users
  mysql_user: name="" state=absent

- name: Remove test database
  mysql_db: name=test state=absent

- name: Update root password
  mysql_user: name=root host={{item}} password={{mysql_new_root_pass.stdout}}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost


- name: Output new root password
  debug: msg="New root password is {{mysql_new_root_pass.stdout}}"




  
# Read more https://github.com/bennojoy/mysql/blob/9a8fe58d227f1bf9798a315d89f6af7984edfeb6/tasks/main.yml
