---
# tasks file for rvm

- name: Add the ondrej PHP PPA
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: Update the apt cache
  become: no
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install PHP
  apt:
    name: php
    state: present

- name: Install PHP package
  apt:
    name={{ item }} state=present
  with_items:
    - php
    - php-fpm
    - php-mysql
    - php-xml

- name: Remove apache2
  apt:
    name: apache2
    state: absent
    