---
# tasks file for zsh-autosuggestions 

- name: Cloning oh-my-zsh
  become: no
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
  register: cloning

  # check lai
- name: Creating new ~/.zshrc
  become: no
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc

- name: zsh-autosuggestions
  become: no
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    update: no

- replace:
    path: ~/.zshrc
    regexp: '^  git$'
    replace: '  git zsh-autosuggestions'

- replace:
    path: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
    regexp: 'fg=8'
    replace: 'fg=blue'
