---

rvm1_temp_download_path: '{{ rvm1_install_path }}/tmp'

rvm1_default_ruby_version: '{{ rvm1_rubies | last if rvm1_rubies and rvm1_rubies is iterable else rvm1_rubies }}'

rvm1_rvm: '{{ rvm1_install_path }}/bin/rvm'

rvm1_symlink_binaries:
  - 'erb'
  - 'executable-hooks-uninstaller'
  - 'gem'
  - 'irb'
  - 'rake'
  - 'rdoc'
  - 'ri'
  - 'ruby'

rvm1_symlink_bundler_binaries:
  - 'bundle'
  - 'bundler'

rvm1_symlink_to: '/usr/local/bin'


rvm1_rvm_latest_installer: 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer'


rvm1_gpg_key_server: 'hkp://keys.gnupg.net'


rvm1_gpg_keys: '409B6B1796C275462A1703113804BB82D39DC0E3'


rvm1_rvm_version: 'stable'


rvm1_install_flags: '--auto-dotfiles --user-install'


rvm1_install_path: '~/.rvm'

rvm1_rvm_check_for_updates: True

rvm1_autolib_mode: 3

